"""Add user profile fields and rename primary key

Revision ID: 5d68775319ab
Revises: c8b7a9b395e0
Create Date: 2025-11-09 17:19:49.472883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d68775319ab'
down_revision = 'c8b7a9b395e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Primero, eliminar la foreign key constraint
    with op.batch_alter_table('auth_local', schema=None) as batch_op:
        batch_op.drop_constraint('auth_local_ibfk_1', type_='foreignkey')
    
    # Renombrar la columna primary key y agregar nuevos campos
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Renombrar user_uuid a uuid
        batch_op.alter_column('user_uuid',
                            new_column_name='uuid',
                            existing_type=sa.String(length=36),
                            nullable=False)
        # Añadir avatar_url
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        # Modificar first_name y last_name para ser opcionales y más largos
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    
    # Recrear la foreign key constraint con el nuevo nombre
    with op.batch_alter_table('auth_local', schema=None) as batch_op:
        batch_op.create_foreign_key('auth_local_user_uuid_fkey', 'users', ['user_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar foreign key constraint
    with op.batch_alter_table('auth_local', schema=None) as batch_op:
        batch_op.drop_constraint('auth_local_user_uuid_fkey', type_='foreignkey')
    
    # Revertir cambios en la tabla users
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Renombrar uuid de vuelta a user_uuid
        batch_op.alter_column('uuid',
                            new_column_name='user_uuid',
                            existing_type=sa.String(length=36),
                            nullable=False)
        # Revertir campos first_name y last_name
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        # Eliminar avatar_url
        batch_op.drop_column('avatar_url')
    
    # Recrear foreign key constraint original
    with op.batch_alter_table('auth_local', schema=None) as batch_op:
        batch_op.create_foreign_key('auth_local_ibfk_1', 'users', ['user_uuid'], ['user_uuid'])

    # ### end Alembic commands ###
