"""Add friendship model for user relationships

Revision ID: 9e7b97ed967c
Revises: 5d68775319ab
Create Date: 2025-11-11 18:57:00.147152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e7b97ed967c'
down_revision = '5d68775319ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_low_id', mysql.CHAR(length=36), nullable=False, comment='UUID del usuario con ID menor'),
    sa.Column('user_high_id', mysql.CHAR(length=36), nullable=False, comment='UUID del usuario con ID mayor'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado: pending|accepted|rejected|removed'),
    sa.Column('requested_by_id', mysql.CHAR(length=36), nullable=False, comment='UUID del usuario que hizo la solicitud'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación de la relación'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('user_low_id', 'user_high_id'),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index('idx_friendship_requested_by', ['requested_by_id'], unique=False)
        batch_op.create_index('idx_friendship_status', ['status'], unique=False)
        batch_op.create_index('idx_friendship_user_high', ['user_high_id'], unique=False)
        batch_op.create_index('idx_friendship_user_low', ['user_low_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index('idx_friendship_user_low')
        batch_op.drop_index('idx_friendship_user_high')
        batch_op.drop_index('idx_friendship_status')
        batch_op.drop_index('idx_friendship_requested_by')

    op.drop_table('friendships')
    # ### end Alembic commands ###
